import { useState, type FormEvent } from 'react'
import { useMutation,useQueryClient } from '@tanstack/react-query'
import { ArrowRight,Waypoints } from 'lucide-react'
import { api,setCSRF } from '../api'
import type { Session } from '../model'
import {NewPasswordField} from '../components/NewPasswordField'
import {validNewPassword} from '../password'
import { Button } from '../components/ui/button'
import { ErrorBox } from '../components/shared'
import {isStaticDemo} from '../request'
export function Login(){const [username,setUsername]=useState('admin');const [password,setPassword]=useState(isStaticDemo?'demo-password':'');const qc=useQueryClient();const login=useMutation({mutationFn:()=>api<Session>('/auth/login',{method:'POST',body:{username,password}}),onSuccess:s=>{setPassword('');setCSRF(s.csrf);qc.setQueryData(['session'],s)}});function submit(e:FormEvent){e.preventDefault();login.mutate()}
 return <div className="login-screen"><div className="login-panel"><form onSubmit={submit}><div className="brand"><Waypoints size={28}/><span>Caddy Admin</span></div><h2>管理员登录</h2><ErrorBox error={login.error}/><label>管理员账号<input autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)} required maxLength={64}/></label><label>密码<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required maxLength={256}/></label><Button className="full" type="submit" disabled={login.isPending}>{login.isPending?'正在登录…':'登录控制台'}<ArrowRight size={16}/></Button><a className="portal-login-link" href="/portal">无需登录，查看服务导览 <ArrowRight size={15}/></a><p className="login-help">账号由部署者初始化。忘记密码时，请使用服务器上的密码重置命令。</p></form></div></div>
}
export function PasswordForm({required=false,onDone}:{required?:boolean;onDone:()=>void}){const [current,setCurrent]=useState('');const [password,setPassword]=useState('');const [confirm,setConfirm]=useState('');const m=useMutation({mutationFn:async()=>{if(!validNewPassword(password))throw new Error('密码至少 8 个字符，最多 256 字节');if(password!==confirm)throw new Error('两次输入的密码不一致');return api('/auth/password',{method:'POST',body:{current,password}})},onSuccess:()=>{setCSRF('');onDone()}});return <form className="password-form" onSubmit={e=>{e.preventDefault();m.mutate()}}><h2>{required?'修改初始密码':'修改管理员密码'}</h2><p className="muted">密码至少 8 个字符。修改后所有旧会话失效，请重新登录。</p><ErrorBox error={m.error}/><label>当前密码<input type="password" autoComplete="current-password" required value={current} onChange={e=>setCurrent(e.target.value)}/></label><NewPasswordField label="新密码" value={password} onChange={setPassword} onGenerate={setConfirm} disabled={m.isPending}/><label>确认新密码<input type="password" autoComplete="new-password" required value={confirm} onChange={e=>setConfirm(e.target.value)}/></label><Button type="submit" disabled={m.isPending||!validNewPassword(password)}>保存新密码</Button></form>}
