import { useState } from 'react'
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query'
import { Link } from '@tanstack/react-router'
import { Plus,Search,Globe,House,MoreHorizontal,Trash2,Power,Pencil,ArrowUpRight } from 'lucide-react'
import { api } from '../api'
import { type Service,type ServiceList,type Settings,filterServices,serviceState,upstream,date } from '../model'
import { Button } from '../components/ui/button'
import { Dialog } from '../components/ui/dialog'
import { Heading,Loading,ErrorBox,Empty,Badge } from '../components/shared'

const blank:Service={id:'',name:'',group:'homelab',hostname:'',scheme:'http',host:'',port:80,enabled:true,notes:'',dial:'',updated_at:''}

export function Services(){
 const qc=useQueryClient()
 const q=useQuery({queryKey:['services'],queryFn:()=>api<ServiceList>('/services'),refetchInterval:15000})
 const settings=useQuery({queryKey:['settings'],queryFn:()=>api<Settings>('/settings')})
 const [keyword,setKeyword]=useState(''),[group,setGroup]=useState(''),[state,setState]=useState('')
 const [editor,setEditor]=useState<{service:Service;revision:number}|null>(null),[remove,setRemove]=useState<{service:Service;revision:number}|null>(null)
 const change=useMutation({mutationFn:({service,revision,method}:{service:Service;revision:number;method:string})=>api('/services'+(method==='POST'?'':`/${service.id}`),{method,body:{service,revision}}),onSuccess:()=>{setEditor(null);setRemove(null);qc.invalidateQueries({queryKey:['services']});qc.invalidateQueries({queryKey:['overview']});qc.invalidateQueries({queryKey:['preview']})}})
 const d=q.data,list=d?filterServices(d.services,keyword,group,state):[],deleted=d?.published.filter(s=>!d.services.some(x=>x.id===s.id))??[]
 function openNew(){if(d){change.reset();setEditor({service:{...blank},revision:d.revision})}}
 return <>
  <Heading title="服务" description="为你的应用配置域名与上游，所有修改先保存为草稿。" action={<Button disabled={!d} onClick={openNew}><Plus size={17}/>新建服务</Button>}/>
  <ErrorBox error={q.error} onRetry={()=>void q.refetch()}/><ErrorBox error={!editor&&!remove?change.error:null}/>
  <div className="notice notice-neutral"><LayersIcon/><span>草稿修订 <strong>r{d?.revision??'—'}</strong> · 保存不会立即影响线上服务。</span><Link to="/deployments" className="text-link">预览与发布 <ArrowUpRight size={14}/></Link></div>
  <section className="card">
   <div className="filters"><div className="search"><Search size={17}/><input aria-label="搜索服务" placeholder="搜索名称、域名或上游…" value={keyword} onChange={e=>setKeyword(e.target.value)}/></div><select aria-label="按分组筛选" value={group} onChange={e=>setGroup(e.target.value)}><option value="">所有分组</option><option value="public">Public</option><option value="homelab">Homelab</option></select><select aria-label="按状态筛选" value={state} onChange={e=>setState(e.target.value)}><option value="">所有状态</option><option value="enabled">已启用</option><option value="disabled">已停用</option></select></div>
   {q.isPending?<Loading/>:!list.length?<Empty title={d?.services.length?'没有匹配的服务':'添加你的第一个服务'} action={!d?.services.length?<Button onClick={openNew}>添加第一个服务</Button>:undefined}>从一个域名和一个上游地址开始。</Empty>:<div className="table-wrap"><table><thead><tr><th>服务 / 域名</th><th>分组</th><th>上游地址</th><th>草稿状态</th><th>线上状态</th><th>操作</th></tr></thead><tbody>{list.map(s=><tr key={s.id}><td><div className="service-name"><span className="service-icon">{s.group==='homelab'?<House size={19}/>:<Globe size={19}/>}</span><div><strong>{s.name}</strong><small className="mono">{s.hostname}</small></div></div><small>更新于 {date(s.updated_at)}</small></td><td><Badge>{s.group==='public'?'Public':'Homelab'}</Badge></td><td><code>{upstream(s)}</code><small>生效目标：{s.dial||'发布前解析'}</small></td><td><Badge tone={s.enabled?'green':'neutral'}>{s.enabled?'已启用':'已停用'}</Badge><small>{serviceState(s,d!.published)}</small></td><td>{d!.published.find(x=>x.id===s.id)?.enabled?<Badge tone="green">路由已发布</Badge>:<Badge>未暴露</Badge>}<small>上游健康：未检测</small></td><td><div className="row-actions"><Button variant="ghost" size="sm" aria-label={`编辑 ${s.name}`} onClick={()=>{change.reset();setEditor({service:{...s},revision:d!.revision})}}><Pencil size={16}/></Button><Button variant="ghost" size="sm" aria-label={`${s.enabled?'停用':'启用'} ${s.name}`} disabled={change.isPending} onClick={()=>change.mutate({service:{...s,enabled:!s.enabled},revision:d!.revision,method:'PUT'})}><Power size={16}/></Button><Button variant="ghost" size="sm" aria-label={`删除 ${s.name}`} onClick={()=>{change.reset();setRemove({service:s,revision:d!.revision})}}><Trash2 size={16}/></Button></div></td></tr>)}</tbody></table></div>}
   <div className="table-footer">{list.length} 个服务 · Public 服务允许公网访问，Homelab 受 LAN/VPN 策略限制</div>
  </section>
  {deleted.length>0&&<div className="notice notice-amber">待发布删除：{deleted.map(s=>s.hostname).join('、')}。这些路由目前仍在线上生效。</div>}
  <Dialog open={!!editor} onOpenChange={v=>{if(!v&&!change.isPending)setEditor(null)}} title={editor?.service.id?'编辑服务':'新建服务'} description="保存为草稿后，在发布页面完成校验和确认。">{editor&&<form onSubmit={event=>{event.preventDefault();change.mutate({...editor,method:editor.service.id?'PUT':'POST'})}}><ErrorBox error={change.error}/><div className="form-grid"><label className="span-2">服务名称<input value={editor.service.name} required maxLength={100} placeholder="例如：Immich 相册" onChange={e=>setEditor({...editor,service:{...editor.service,name:e.target.value}})}/></label><label>域名分组<select value={editor.service.group} onChange={e=>setEditor({...editor,service:{...editor.service,group:e.target.value as Service['group']}})}><option value="homelab">Homelab · 内部访问</option><option value="public" disabled={!settings.data?.config.public_domain}>Public · 公网访问</option></select>{!settings.isPending&&!settings.data?.config.public_domain&&<small>公网域名尚未配置，暂时只能创建 Homelab 服务。</small>}</label><label>完整域名<input value={editor.service.hostname} required placeholder={`photo.${editor.service.group==='public'?(settings.data?.config.public_domain||'public.example.com'):(settings.data?.config.homelab_domain??'home.example.com')}`} onChange={e=>setEditor({...editor,service:{...editor.service,hostname:e.target.value}})}/></label><label>上游协议<select value={editor.service.scheme} onChange={e=>setEditor({...editor,service:{...editor.service,scheme:e.target.value as Service['scheme']}})}><option value="http">HTTP</option><option value="https">HTTPS · 验证证书</option></select></label><label>端口<input type="number" min={1} max={65535} required value={editor.service.port} onChange={e=>setEditor({...editor,service:{...editor.service,port:Number(e.target.value)}})}/></label><label className="span-2">上游主机<input required placeholder="10.0.0.8 或已许可的服务名" value={editor.service.host} onChange={e=>setEditor({...editor,service:{...editor.service,host:e.target.value}})}/></label><label className="span-2">备注<textarea maxLength={2000} value={editor.service.notes} onChange={e=>setEditor({...editor,service:{...editor.service,notes:e.target.value}})}/></label></div><label className="checkbox"><input type="checkbox" checked={editor.service.enabled} onChange={e=>setEditor({...editor,service:{...editor.service,enabled:e.target.checked}})}/>发布后启用此服务</label><div className="route-preview"><span>{editor.service.hostname.toLowerCase().trim()||'你的域名'}</span><span>→</span><code>{upstream(editor.service)}</code></div><div className="dialog-actions"><Button variant="outline" type="button" disabled={change.isPending} onClick={()=>setEditor(null)}>取消</Button><Button type="submit" disabled={change.isPending}>{change.isPending?'保存中…':'保存草稿'}</Button></div></form>}</Dialog>
  <Dialog open={!!remove} onOpenChange={v=>{if(!v&&!change.isPending)setRemove(null)}} title="删除服务" description={`${remove?.service.hostname??''} 将从草稿移除。线上路由在再次发布前仍然保留。`}><ErrorBox error={change.error}/><div className="dialog-actions"><Button variant="outline" disabled={change.isPending} onClick={()=>setRemove(null)}>取消</Button><Button variant="destructive" disabled={change.isPending} onClick={()=>remove&&change.mutate({...remove,method:'DELETE'})}>确认删除</Button></div></Dialog>
 </>
}
function LayersIcon(){return <MoreHorizontal size={20}/>}
