import {DomainDNS} from '../components/DomainDNS'
import {CloudflareTokenHelp} from '../components/CloudflareTokenHelp'
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query'
import {useState} from 'react'
import {api} from '../api'
import {accessLabel,exposureChanges,type ManagedSettings,type Settings as SettingsData} from '../model'
import {Heading,ErrorBox,Loading,Badge} from '../components/shared'
import {ConfigurationTransfer} from '../components/ConfigurationTransfer'
import {PasswordForm} from './Login'
const list=(value:string)=>value.split(/[\n,]/).map(v=>v.trim()).filter(Boolean)
export function Settings(){
 const qc=useQueryClient()
 const q=useQuery({queryKey:['settings'],queryFn:()=>api<SettingsData>('/settings'),refetchInterval:query=>query.state.data?.certificate_status.mode==='cloudflare'&&query.state.data.certificate_status.public_status==='pending'?5000:false})
 const [rawLists,setRawLists]=useState<Partial<Record<'lan_cidrs'|'upstream_cidrs'|'allowed_names'|'denied_ips'|'resolvers',string>>>({})
 const [token,setToken]=useState(''),[message,setMessage]=useState(''),[draft,setDraft]=useState<ManagedSettings|null>(null),[revision,setRevision]=useState(0),[confirmExposure,setConfirmExposure]=useState(false),[confirmTransition,setConfirmTransition]=useState(false),[confirmRemoval,setConfirmRemoval]=useState<string|null>(null)
 const activate=useMutation({mutationFn:()=>api<{restart_required:boolean}>('/settings/cloudflare',{method:'POST',body:{token,enable:true}}),onSuccess:result=>{setToken('');setMessage(result.restart_required?'Cloudflare 配置已保存，服务正在安全重启；临时证书会保持管理入口可访问。':'Cloudflare 配置已保存。请按当前部署方式重启服务以应用新 Token。');void qc.invalidateQueries({queryKey:['settings']})}})
 const save=useMutation({mutationFn:()=>api('/settings',{method:'PUT',body:{revision,settings:draft,confirm_exposure:confirmExposure}}),onSuccess:()=>{setDraft(null);setRawLists({});setConfirmExposure(false);setMessage('设置草稿已保存，尚未影响线上。请到发布页预览、校验并确认发布。');for(const key of ['settings','services','overview','preview'])void qc.invalidateQueries({queryKey:[key]})}})
 const transition=useMutation({mutationFn:()=>api('/settings/console/complete',{method:'POST',body:{revision:q.data!.revision,confirm:true}}),onSuccess:()=>{setConfirmTransition(false);setMessage('旧控制台入口移除已保存为草稿；请预览、校验并发布以完成交接。');for(const key of ['settings','preview','overview'])void qc.invalidateQueries({queryKey:[key]})}})
 const d=q.data,policy=draft??d?.config
 const active=d?.active_config??d?.config
 const exposure=!!(draft&&d&&exposureChanges(d.active_config??d.config,draft))
 function edit(next:ManagedSettings){const {test_tls:_,...clean}=next as ManagedSettings&{test_tls?:boolean};if(!draft)setRevision(d!.revision);setDraft(clean);setConfirmExposure(false);save.reset();setMessage('')}
 const canConfigure=d&&!d.external_caddy&&!d.config.test_tls&&d.certificate_status.activation_status!=='applying'&&d.certificate_status.activation_status!=='uncertain'
 return <><Heading title="设置" description="域名与访问策略先保存为草稿，通过校验与确认发布后才生效。"/><ErrorBox error={q.error} onRetry={()=>void q.refetch()}/>{q.isPending?<Loading/>:d&&policy&&<>
  <section className="card settings-card"><h2>域名与访问策略 <Badge>草稿 r{d.revision}</Badge></h2><p className="muted">保存不立即影响线上。业务访问属性与可选的控制台来源限制独立配置。</p>{active&&JSON.stringify(d.config.domains)!==JSON.stringify(active.domains)&&<p className="notice notice-amber">域名设置有未发布修改。</p>}
  <form onSubmit={e=>{e.preventDefault();save.mutate()}}>
  {policy.domains.map(domain=><div className="form-grid" key={domain.id}><label>基础域名<input aria-label={`基础域名 ${domain.id}`} value={domain.name} onChange={e=>edit({...policy,domains:policy.domains.map(x=>x.id===domain.id?{...x,name:e.target.value}:x)})}/></label><label>访问范围<select aria-label={`访问范围 ${domain.id}`} value={domain.access??''} onChange={e=>edit({...policy,domains:policy.domains.map(x=>x.id===domain.id?{...x,access:e.target.value?e.target.value as 'trusted'|'internet':null}:x)})}><option value="">待配置</option><option value="trusted">仅可信网络</option><option value="internet">允许互联网访问</option></select><small>{accessLabel(domain.access)}</small></label>{confirmRemoval===domain.id?<div className="span-2 notice notice-amber">确认从设置草稿删除 {domain.name}？有服务或控制台引用时服务器会拒绝。<button type="button" className="button button-danger" onClick={()=>{edit({...policy,domains:policy.domains.filter(x=>x.id!==domain.id)});setConfirmRemoval(null)}}>确认删除域名</button><button type="button" className="button button-outline" onClick={()=>setConfirmRemoval(null)}>取消</button></div>:<button type="button" className="button button-outline" onClick={()=>setConfirmRemoval(domain.id)}>删除域名</button>}</div>)}
  <button type="button" className="button button-outline" onClick={()=>edit({...policy,domains:[...policy.domains,{id:crypto.randomUUID(),name:'',access:null}]})}>添加域名</button>
  <h3>控制台</h3><label>控制台完整域名<input value={policy.admin_domain} onChange={e=>edit({...policy,admin_domain:e.target.value,origin:`https://${e.target.value.trim().toLowerCase()}`})}/></label><p className="muted">修改后发布将保留旧入口；从新地址登录并明确完成交接，再发布移除旧入口。</p><label className="checkbox"><input type="checkbox" checked={policy.console_lan_only} onChange={e=>edit({...policy,console_lan_only:e.target.checked})}/>仅允许 LAN/VPN 访问控制台</label>
  <label>可信网络 CIDR<input placeholder="例如：192.168.1.0/24，10.0.0.0/8" value={rawLists.lan_cidrs??policy.lan_cidrs.join(',')} onChange={e=>{setRawLists({...rawLists,lan_cidrs:e.target.value});edit({...policy,lan_cidrs:list(e.target.value)})}}/></label><small>选择仅可信网络的业务域名或启用控制台限制时需要填写；填写网段不会自动启用控制台限制。</small>
  <h3>上游许可</h3><label>允许上游网段<input value={rawLists.upstream_cidrs??policy.upstream_cidrs.join(',')} onChange={e=>{setRawLists({...rawLists,upstream_cidrs:e.target.value});edit({...policy,upstream_cidrs:list(e.target.value)})}}/></label><label>许可服务名<input value={rawLists.allowed_names??policy.allowed_names.join(',')} onChange={e=>{setRawLists({...rawLists,allowed_names:e.target.value});edit({...policy,allowed_names:list(e.target.value)})}}/></label><p className="muted">两项均为空时不许可任何代理目标。首次配置请先发布许可，再添加服务。</p>
  <details><summary>高级：额外禁止目标</summary><label>禁止的上游 IP<input value={rawLists.denied_ips??policy.denied_ips.join(',')} onChange={e=>{setRawLists({...rawLists,denied_ips:e.target.value});edit({...policy,denied_ips:list(e.target.value)})}}/></label></details>
  <h3>服务器 DNS</h3><label>DNS 解析器<input value={rawLists.resolvers??policy.resolvers.join(',')} onChange={e=>{setRawLists({...rawLists,resolvers:e.target.value});edit({...policy,resolvers:list(e.target.value)})}}/></label><p className="muted">用于证书 DNS 校验和运行诊断，与浏览器 DoH 独立；不替代系统上游解析器。保存设置不会修改外部 DNS，请核对各域名解析及 Token 授权。</p>
  {policy.admin_domain!==d.config.admin_domain&&<p className="notice notice-amber">将启用新控制台 https://{policy.admin_domain}；旧入口会继续保留，需在新入口登录后完成交接。</p>}
  {exposure&&<label className="checkbox warning"><input type="checkbox" checked={confirmExposure} onChange={e=>setConfirmExposure(e.target.checked)}/>我已核对影响，确认放开业务或控制台访问范围。</label>}
  <ErrorBox error={save.error}/><div className="release-actions"><button type="button" className="button button-outline" disabled={save.isPending||!draft} onClick={()=>{setDraft(null);setRawLists({});setConfirmExposure(false)}}>放弃修改</button><button className="button button-primary" type="submit" disabled={!draft||save.isPending||exposure&&!confirmExposure}>{save.isPending?'保存中…':'保存设置草稿'}</button></div></form>
  {active?.previous_admin_domain&&<div className="notice notice-amber"><p>控制台交接中：旧入口 {active.previous_admin_domain} → 新入口 {active.admin_domain}。</p><a href={active.origin}>打开新控制台并登录</a>{location.origin===active.origin&&<><label className="checkbox"><input type="checkbox" checked={confirmTransition} onChange={e=>setConfirmTransition(e.target.checked)}/>我已从新控制台登录，确认移除旧入口</label><button className="button button-primary" disabled={!confirmTransition||transition.isPending} onClick={()=>transition.mutate()}>完成控制台交接</button></>}<ErrorBox error={transition.error}/></div>}
  </section>
  {!d.external_caddy&&!d.config.test_tls&&d.token_configured&&<DomainDNS key={d.revision} domains={d.config.domains}/>}
  <section className="card settings-card"><h2>部署信息</h2><dl>{[['Manager 版本',d.manager_version],['Caddy 版本',d.caddy_version],['部署模式',d.external_caddy?'外部 Caddy':'内置 Caddy'],['Cloudflare DNS 模块',d.cloudflare_module?'已包含':'不可用 / 无法确认'],['Cloudflare Token',d.token_configured?'已配置（隐藏）':'未配置'],['已生效控制台',active?.admin_domain??d.config.admin_domain]].map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl>{d.config.test_tls&&<div className="notice notice-amber">当前为隔离测试 TLS 模式，使用 Caddy 内部 CA，不代表公网可信证书。</div>}<div className="notice notice-amber">证书策略：{d.certificate_status.mode==='bootstrap_internal'?'内部引导证书':'Cloudflare DNS-01'}；公网证书：{d.certificate_status.public_status==='ready'?'已验证可信':d.certificate_status.public_status==='error'?'检测异常':'等待签发或验证'}。{d.certificate_status.mode==='cloudflare'&&d.certificate_status.public_status!=='ready'?'临时证书保持管理入口可访问，浏览器可能显示信任警告。':''}{d.certificate_status.activation_status==='uncertain'?'上次切换结果待核对，请检查运行状态后按运维文档恢复。':''}</div>
  {canConfigure&&<form onSubmit={e=>{e.preventDefault();setMessage('');activate.mutate()}}><h3>{d.certificate_status.mode==='bootstrap_internal'?'启用':'更新'} Cloudflare 公网证书</h3><p className="muted">Token 保存在权限受限的 secret 文件中。请确认所有登记域名均在授权范围内。</p><label>Cloudflare API Token<input aria-label="Cloudflare API Token" type="password" autoComplete="off" value={token} onChange={e=>setToken(e.target.value)}/></label><CloudflareTokenHelp/><button className="button button-primary" type="submit" disabled={!token||activate.isPending}>{activate.isPending?'正在应用…':'保存并启用'}</button></form>}<ErrorBox error={activate.error} onRetry={()=>activate.mutate()}/></section>
  {message&&<p className="notice notice-green" role="status">{message}</p>}<ConfigurationTransfer/><section className="card settings-card"><PasswordForm onDone={()=>{qc.clear();window.dispatchEvent(new Event('session-expired'))}}/></section>
 </>}</>
}
