import {useEffect,useMemo,useState} from 'react'
import {Waypoints} from 'lucide-react'
import {SetupDNSGuidance,suggestedDNSAddress} from '../components/SetupDNSGuidance'

import {ConfigurationFile} from '../components/ConfigurationFile'
import {setupConfiguration,type Configuration} from '../configuration'

type Form={username:string;password:string;homelabDomain:string;lan:string;upstream:string;allowed:string;denied:string;resolvers:string}
type Check={id:string;status:'pass'|'warning'|'block';message:string}
type Preflight={normalized:{admin_domain:string;origin:string;admin_origin:string};network_valid:boolean;network_error?:string;checks:Check[];can_complete:boolean;requires_acknowledgement:boolean}
type Handoff={initialized:boolean;mode:'embedded'|'external';admin_origin:string;manager_status:'ready'|'pending'|'error';dns_status:'ready'|'pending'|'error';console_status:'ready'|'pending'|'error';temporary_entry:boolean;checked_at:string}
const initial:Form={username:'admin',password:'',homelabDomain:'',lan:'',upstream:'',allowed:'',denied:'',resolvers:''}
const labels=['管理员','域名','网络','DNS','确认']
const list=(value:string)=>value.split(',').map(v=>v.trim()).filter(Boolean)
const normalizeDomain=(value:string)=>value.trim().toLowerCase().replace(/\.+$/,'')
class SetupHTTPError extends Error {}
async function json(response:Response){const body=await response.json().catch(()=>null);if(!response.ok)throw new SetupHTTPError(body?.error?.message??`请求失败（HTTP ${response.status}）`);return body}

export function Setup({pollLogin=true}:{pollLogin?:boolean}){
 const [importFile,setImportFile]=useState<Configuration|null>(null),[importCandidate,setImportCandidate]=useState<Configuration|null>(null),[importName,setImportName]=useState(''),[confirmImport,setConfirmImport]=useState(false)
 const [step,setStep]=useState(0),[form,setForm]=useState(initial),[error,setError]=useState(''),[checking,setChecking]=useState(true),[externalCaddy,setExternalCaddy]=useState(false),[initialized,setInitialized]=useState(false)
 const [suggestions,setSuggestions]=useState<string[]>([]),[clientIP,setClientIP]=useState(''),[preflight,setPreflight]=useState<Preflight|null>(null),[ack,setAck]=useState(false),[submitting,setSubmitting]=useState(false)
 const [preflightBusy,setPreflightBusy]=useState(false)
 const [dnsAddress,setDNSAddress]=useState('')
 const [recovering,setRecovering]=useState(false)
 const [adminOrigin,setAdminOrigin]=useState(''),[handoff,setHandoff]=useState<Handoff|null>(null),[handoffOffline,setHandoffOffline]=useState(false),[countdown,setCountdown]=useState(3),[autoJump,setAutoJump]=useState(true)
 useEffect(()=>{let alive=true;void(async()=>{try{const body=await json(await fetch('/api/v1/setup/status'));if(alive){setExternalCaddy(body.external_caddy===true);setDNSAddress(body.external_caddy===true?'':suggestedDNSAddress(location.hostname));setInitialized(body.initialized===true);if(body.initialized===true)setRecovering(true);setSuggestions(Array.isArray(body.resolver_suggestions)?body.resolver_suggestions:[]);setClientIP(body.client_ip??'');setError('')}}catch{try{const state=await json(await fetch('/api/v1/setup/handoff',{cache:'no-store'})) as Handoff;if(alive){setHandoff(state);setExternalCaddy(state.mode==='external');setAdminOrigin(state.admin_origin);setError('')}}catch{if(alive){setRecovering(true);setHandoffOffline(true)}}}finally{if(alive)setChecking(false)}})();return()=>{alive=false}},[])
 useEffect(()=>{if((!adminOrigin&&!recovering)||!pollLogin)return;let alive=true;const poll=async()=>{try{const value=await json(await fetch('/api/v1/setup/handoff',{cache:'no-store'})) as Handoff;if(alive){setHandoff(value);setAdminOrigin(value.admin_origin);setExternalCaddy(value.mode==='external');setHandoffOffline(false)}}catch{if(alive)setHandoffOffline(true);if(recovering){try{const value=await json(await fetch('/api/v1/setup/status'));if(alive&&value.initialized===false){setRecovering(false);setAdminOrigin('');setError('初始化尚未完成，已保留输入，请检查后重新提交。')}}catch{/* Listener may still be restarting. */}}}};void poll();const timer=window.setInterval(()=>void poll(),2000);return()=>{alive=false;window.clearInterval(timer)}},[adminOrigin,recovering,pollLogin])
 useEffect(()=>{if(handoff?.console_status!=='ready'||!autoJump)return;setCountdown(3);const timer=window.setInterval(()=>setCountdown(value=>{if(value<=1){window.clearInterval(timer);location.assign(handoff.admin_origin+'/');return 0}return value-1}),1000);return()=>window.clearInterval(timer)},[handoff?.console_status,handoff?.admin_origin,autoJump])
 const settings=useMemo(()=>({homelab_domain:form.homelabDomain,lan_cidrs:list(form.lan),upstream_cidrs:list(form.upstream),allowed_names:list(form.allowed),denied_ips:list(form.denied),resolvers:list(form.resolvers)}),[form])
 const field=(key:keyof Form)=>(e:React.ChangeEvent<HTMLInputElement>)=>{setForm({...form,[key]:e.target.value});setPreflight(null);setAck(false);setConfirmImport(false)}
 const adminDomain=normalizeDomain(form.homelabDomain)?`caddyadmin.${normalizeDomain(form.homelabDomain)}`:''
 async function runPreflight(){setPreflightBusy(true);setError('');try{const result=await json(await fetch('/api/v1/setup/preflight',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({settings,...(importFile?{services:importFile.services}:{})})})) as Preflight;setPreflight(result);return result}catch(e){setError(e instanceof Error?e.message:'预检失败，请重试');return null}finally{setPreflightBusy(false)}}
 async function next(){if(step===2){const result=await runPreflight();if(result?.network_valid){setStep(3);setError('')}else if(result)setError(result.network_error||'请检查网络设置');return}if(step!==3){setStep(step+1);return}const result=await runPreflight();if(result?.can_complete)setStep(4)}
 async function submit(){setSubmitting(true);setError('');try{const latest=await runPreflight();if(!latest?.can_complete)return;if(latest.requires_acknowledgement&&!ack){setError('请先确认预检警告');return}const data=await json(await fetch('/api/v1/setup/complete',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:form.username,password:form.password,settings,acknowledge_warnings:ack,...(importFile?{services:importFile.services,confirm_import:confirmImport}:{})})}));if(typeof data.admin_origin==='string')setAdminOrigin(data.admin_origin)}catch(e){if(e instanceof SetupHTTPError){setError(e.message)}else{setRecovering(true);setHandoffOffline(true)}}finally{setSubmitting(false)}}
 if(adminOrigin||recovering)return <div className="setup-screen"><section className="setup-card"><Waypoints size={38}/><h1>{handoff?.console_status==='ready'?'正式控制台已就绪':'服务正在重启'}</h1><p className="muted">正在核对初始化结果，不会自动重复提交。正式入口：<strong>{adminOrigin||'等待交接服务返回地址'}</strong></p>{handoffOffline&&<div className="notice notice-amber">暂时无法读取交接状态；服务可能仍在重启，页面会继续查询。</div>}<dl><div><dt>Manager</dt><dd>{handoff?.manager_status??'pending'}</dd></div><div><dt>服务端 DNS</dt><dd>{handoff?.dns_status??'pending'}</dd></div><div><dt>TLS 与路由</dt><dd>{handoff?.console_status??'pending'}</dd></div></dl>{handoff?.dns_status==='ready'&&handoff.console_status!=='ready'&&<p className="notice notice-amber">服务器已能解析域名，但可信 TLS 或控制台路由尚未就绪。</p>}<div className="setup-actions"><button className="button button-outline" disabled={!adminOrigin} onClick={()=>navigator.clipboard?.writeText(adminOrigin)}>复制地址</button>{adminOrigin&&!externalCaddy&&<a className="button button-outline" href="/">通过临时入口继续登录</a>}{adminOrigin&&<a className="button button-primary" href={adminOrigin+'/'}>立即打开</a>}</div>{handoff?.console_status==='ready'&&<p className="muted">{autoJump?`${countdown} 秒后自动打开正式入口。`:"已取消自动跳转。"} {autoJump&&<button className="button button-ghost" onClick={()=>setAutoJump(false)}>取消自动跳转</button>}</p>}</section></div>
 if(checking)return <div className="setup-screen"><div className="setup-card"><h1>正在检查初始化状态</h1><p className="muted">请稍候…</p></div></div>
 if(initialized)return <div className="setup-screen"><div className="setup-card"><h1>系统已经初始化</h1><p className="muted">请使用配置的控制台域名进入登录页面。</p></div></div>
 const blocks=preflight?.checks.filter(check=>check.status==='block')??[],warnings=preflight?.checks.filter(check=>check.status==='warning')??[]
 return <div className="setup-screen"><section className="setup-card"><div className="setup-brand"><Waypoints/><span>Caddy Admin</span></div><p className="eyebrow">FIRST RUN</p><h1>初始化 Caddy Admin</h1><p className="muted">配置只保存在你的服务器中。完成前不会启动 Caddy 或开放业务接口。</p><div className="notice notice-amber">初始化页面可由可信内网访问；第一个成功提交者将成为管理员。请立即完成初始化，不要把初始化端口暴露到公网。</div><ol className="setup-steps">{labels.map((label,index)=><li key={label} className={index===step?'active':index<step?'done':''}><b>{index+1}</b>{label}</li>)}</ol>{error&&<div className="notice notice-red" role="alert">{error}</div>}<div className="setup-form">
 {step===0&&<><details><summary>从导出的配置初始化</summary><p className="muted">导入域名、网络策略和服务草稿；管理员密码与 Cloudflare Token 需重新设置。服务不会自动发布。</p><ConfigurationFile onSelect={()=>setImportCandidate(null)} onLoad={(value,name)=>{setImportCandidate(value);setImportName(name);setError('')}}/>{importCandidate&&<><p>{importName}：{importCandidate.settings.homelab_domain}，{importCandidate.services.length} 个服务</p><button className="button button-outline" onClick={()=>{try{const s=setupConfiguration(importCandidate);setForm({...form,homelabDomain:s.homelab_domain,lan:s.lan_cidrs.join(','),upstream:s.upstream_cidrs.join(','),allowed:s.allowed_names.join(','),denied:s.denied_ips.join(','),resolvers:s.resolvers.join(',')});setImportFile(importCandidate);setImportCandidate(null);setConfirmImport(false);setPreflight(null);setAck(false);setError('')}catch(e){setError(e instanceof Error?e.message:'无法采用该配置')}}}>采用导入配置</button></>}</details>{importFile&&<p role="status" className="notice notice-green">已采用配置：{importFile.services.length} 个服务将保存为草稿。</p>}<h2>创建管理员</h2><label>管理员用户名<input value={form.username} onChange={field('username')} autoComplete="username"/></label><label>管理员密码<input aria-label="管理员密码" type="password" value={form.password} onChange={field('password')} autoComplete="new-password"/><small>至少 12 字节；不会写入环境变量或日志。</small></label></>}
 {step===1&&<><h2>设置 Homelab 域名</h2><label>Homelab 域名<input aria-label="Homelab 域名" placeholder="home.example.com" value={form.homelabDomain} onChange={field('homelabDomain')}/><small>控制台域名将自动设为 {adminDomain||'caddyadmin.home.example.com'}；Public 域名可在后续版本中配置。</small></label></>}
 {step===2&&<><h2>限制网络范围</h2><label>可信网络 CIDR<input aria-label="可信网络 CIDR" required placeholder="10.0.0.0/8" value={form.lan} onChange={field('lan')}/><small>仅填写实际需要访问控制台和 Homelab 服务的 LAN/VPN 网段。</small></label><label>上游网络 CIDR<input aria-label="上游网络 CIDR" required placeholder="10.0.0.0/8" value={form.upstream} onChange={field('upstream')}/><small>仅填写允许作为反向代理上游的网段；不会默认放开全部私网。</small></label>{clientIP&&<p className="muted">服务器看到的来源地址：{clientIP}。Docker 或 NAT 可能使它不同于设备地址。</p>}<details><summary>高级网络规则</summary><label>允许的上游名称（逗号分隔）<input value={form.allowed} onChange={field('allowed')}/></label><label>拒绝的目标 IP（逗号分隔）<input value={form.denied} onChange={field('denied')}/></label></details></>}
 {step===3&&<><h2>DNS</h2><SetupDNSGuidance domain={normalizeDomain(form.homelabDomain)} address={dnsAddress} onAddressChange={setDNSAddress} externalCaddy={externalCaddy}/><label>DNS 解析器（逗号分隔）<input aria-label="DNS 解析器（逗号分隔）" required placeholder="例如：192.168.1.1" value={form.resolvers} onChange={field('resolvers')}/><small>填写当前网络中可信且可达的 DNS 解析器 IP；项目不会预设外部 DNS 服务。</small></label>{suggestions.length>0&&<div><p className="muted">从服务器配置检测到的建议（不会自动采用）：</p>{suggestions.map(value=><button key={value} className="button button-outline" onClick={()=>{setForm({...form,resolvers:value});setPreflight(null)}}>采用 {value}</button>)}</div>}{externalCaddy?<p className="notice notice-amber">证书与 DNS 凭据需在专用外部 Caddy 实例安全配置；本向导不会读取或保存远端密钥。</p>:<p className="notice notice-amber">首次启动使用临时证书，浏览器可能显示信任提示。初始化完成后可在设置页配置 Cloudflare Token 并启用可信证书。</p>}<button className="button button-outline" disabled={preflightBusy||!list(form.resolvers).length} onClick={()=>void runPreflight()}>{preflightBusy?'正在检查 DNS…':'重新检查 DNS'}</button><p className="muted">检查由服务器通过上述解析器执行；有解析结果不代表指向填写的 IP，也不代表浏览器访问或 HTTPS 已就绪。</p>{preflight?.checks.filter(check=>['resolver_reachable','admin_dns','external_console'].includes(check.id)).map(check=><p key={check.id} role="status" className={`notice notice-${check.status==='pass'?'green':'amber'}`}>{check.message}</p>)}{blocks.map(check=><p className="notice notice-red" key={check.id}>{check.message}</p>)}</>}
 {step===4&&<><h2>确认配置</h2>{importFile&&<><h3>导入服务草稿（{importFile.services.length}）</h3><ul>{importFile.services.map((s,i)=><li key={i}>{s.name} · {s.hostname} · {s.enabled?'启用':'停用'}</li>)}</ul><label className="checkbox warning"><input type="checkbox" checked={confirmImport} onChange={e=>setConfirmImport(e.target.checked)}/>我已确认导入配置，服务仅保存为草稿。</label></>}<dl><div><dt>控制台</dt><dd>{preflight?.normalized.admin_domain||adminDomain}</dd></div><div><dt>Homelab 域名</dt><dd>{normalizeDomain(form.homelabDomain)}</dd></div><div><dt>Public 域名</dt><dd>尚未配置</dd></div><div><dt>可信网络</dt><dd>{form.lan}</dd></div></dl>{warnings.map(check=><div className="notice notice-amber" key={check.id}>{check.message}</div>)}{warnings.length>0&&<label className="checkbox warning"><input type="checkbox" checked={ack} onChange={event=>setAck(event.target.checked)}/>我已理解上述警告，并确认继续初始化。</label>}<div className="notice notice-amber">完成后服务会自动重启；关闭此页面不会取消后台操作。</div></>}
 </div><div className="setup-actions">{step>0&&<button className="button button-outline" onClick={()=>setStep(step-1)}>上一步</button>}<button className="button button-primary" onClick={()=>step<4?void next():void submit()} disabled={submitting||preflightBusy||(step===0&&(!form.username||form.password.length<12))||(step===1&&!normalizeDomain(form.homelabDomain))||(step===2&&(!list(form.lan).length||!list(form.upstream).length))||(step===3&&!list(form.resolvers).length)||(step===4&&(!preflight?.can_complete||warnings.length>0&&!ack||!!importFile&&!confirmImport))}>{submitting?'正在提交…':preflightBusy?'正在预检…':step<4?'下一步':'完成初始化'}</button></div></section></div>
}
