import {useState} from 'react'
import {useQueryClient} from '@tanstack/react-query'
import {api} from '../api'
import {downloadConfiguration,type Configuration,type ConfigurationPreview} from '../configuration'
import {statusLabel,upstream} from '../model'
import {ConfigurationFile} from './ConfigurationFile'
import {ErrorBox} from './shared'
export function ConfigurationTransfer(){
 const qc=useQueryClient();const [file,setFile]=useState<Configuration|null>(null),[name,setName]=useState(''),[preview,setPreview]=useState<ConfigurationPreview|null>(null),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState<Error|null>(null),[message,setMessage]=useState('')
 async function action(kind:'export'|'preview'|'import'){setBusy(true);setError(null);setMessage('');try{if(kind==='export'){downloadConfiguration(await api<Configuration>('/configuration/export'));setMessage('配置已导出。')}else if(kind==='preview'&&file){setPreview(null);setConfirmed(false);setPreview(await api<ConfigurationPreview>('/configuration/preview',{method:'POST',body:{configuration:file}}))}else if(kind==='import'&&file&&preview&&confirmed){await api('/configuration/import',{method:'POST',body:{configuration:file,revision:preview.revision,confirm:true}});setPreview(null);setConfirmed(false);setMessage('服务草稿已替换；请前往发布页校验并确认发布后生效。');for(const key of ['services','preview','overview','audit'])void qc.invalidateQueries({queryKey:[key]})}}catch(e){setError(e instanceof Error?e:new Error('操作失败，请重试'));if(kind==='import'){setConfirmed(false);setPreview(null)}}finally{setBusy(false)}}
 return <section className="card settings-card"><h2>配置导入与导出</h2><p className="muted">导出域名、网络策略和当前服务草稿。文件不包含密码、Token、证书、发布历史或运行数据，请妥善保存其中的内网信息。</p><button className="button button-outline" disabled={busy} onClick={()=>void action('export')}>导出配置</button><p className="notice notice-amber">导入将替换全部服务草稿，保留当前实例的域名和网络策略；线上配置保持当前版本。新实例可在初始化时导入完整配置。</p><ConfigurationFile disabled={busy} onSelect={()=>{setFile(null);setPreview(null);setConfirmed(false);setError(null);setMessage('')}} onLoad={(value,filename)=>{setFile(value);setName(filename);setPreview(null);setConfirmed(false);setError(null);setMessage('')}}/>{file&&<><p>{name}：{file.services.length} 个服务</p><button className="button button-outline" disabled={busy} onClick={()=>void action('preview')}>{busy?'正在处理…':'预览导入'}</button></>}{preview&&<><p>将以文件中的 {preview.services.length} 个服务替换草稿（修订 {preview.revision}）。</p>{preview.changes.length?<ul>{preview.changes.map(change=><li key={change.hostname}>{statusLabel[change.kind]??change.kind}：{change.hostname}{(change.before||change.after)&&<small className="muted"> {change.before?upstream(change.before):'无'} → {change.after?upstream(change.after):'无'}</small>}</li>)}</ul>:<p>服务内容无变化。</p>}<details><summary>查看将导入的服务</summary><ul>{preview.services.map(s=><li key={s.hostname}>{s.name} · {s.hostname} · {upstream(s)} · {s.enabled?'启用':'停用'}{s.notes&&<p className="muted">{s.notes}</p>}</li>)}</ul></details><label className="checkbox warning"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)} disabled={busy}/>我已确认替换当前全部服务草稿。</label><button className="button button-primary" disabled={busy||!confirmed} onClick={()=>void action('import')}>确认导入草稿</button></>}<ErrorBox error={error}/>{message&&<p className="notice notice-green" role="status">{message}</p>}</section>
}
