import {useState} from 'react'
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query'
import {api} from '../api'
import {date,type ServiceList,type TrafficData,type TrafficPoint,type TrafficStats,type ObservationStatus,type AccessEvent,type Alert,type Diagnostics} from '../model'
import {Badge,Empty,ErrorBox,Loading} from './shared'

export const bytes=(value:number)=>{if(!Number.isFinite(value))return '—';const units=['B','KiB','MiB','GiB','TiB'];let i=0;while(value>=1024&&i<units.length-1){value/=1024;i++}return `${value.toFixed(i?1:0)} ${units[i]}`}
const duration=(value:number|null|undefined)=>value==null?'—':value<1?`${(value*1000).toFixed(0)} ms`:`${value.toFixed(2)} s`
export const diagnosticClass:Record<string,string>={acme_rate_limit:'ACME 限速',dns_authorization:'DNS 授权失败',caa:'CAA 限制',dns:'DNS 失败',acme_unknown:'签发失败（原因未确认）'}
const range=()=>{const to=Math.floor(Date.now()/1000);return {from:to-86400,to}}
export function TrafficCards({stats}:{stats?:TrafficStats}){
 return <div className="stats-grid observation-stats">{[{label:'已观测请求',value:stats?Math.round(stats.requests??0).toLocaleString():'—',detail:'业务请求 · 含访问限制 403'},{label:'请求 / 响应体流量',value:stats?`${bytes(stats.request_bytes)} / ${bytes(stats.response_bytes)}`:'—',detail:'体字节数 · 非网卡流量'},{label:'5xx 响应',value:stats?`${Math.round(stats.five_xx??0)}${stats.requests?` · ${(stats.five_xx/stats.requests*100).toFixed(1)}%`:''}`:'—',detail:'已完成请求的服务端错误'},{label:'P95 完整响应时长',value:duration(stats?.p95),detail:stats?.quantile_lower_bound?'高于最高 bucket 时显示下界':'Histogram 插值估算'}].map(s=><section className="stat" key={s.label}><div><span>{s.label}</span></div><strong>{s.value}</strong><small>{s.detail}</small></section>)}</div>
}
export function TrafficSummary(){
 const q=useQuery({queryKey:['traffic-summary'],queryFn:()=>api<TrafficData>('/traffic?'+new URLSearchParams(Object.entries(range()).map(([k,v])=>[k,String(v)]))),refetchInterval:30000})
 return <section className="observation-overview" aria-label="24 小时业务统计"><h2>最近 24 小时业务统计</h2><ErrorBox error={q.error} onRetry={()=>void q.refetch()}/><TrafficCards stats={q.data?.summary}/><p className="muted">统计覆盖率 {Math.round((q.data?.coverage??0)*100)}%；仅反映已采集区间。长连接关闭前不进入完成统计。</p></section>
}
function Trend({title,points,select,format,from,to,step}:{title:string;points:TrafficPoint[];select:(p:TrafficPoint)=>number|null;format:(v:number)=>string;from:number;to:number;step:number}){
 const width=640,height=150,pad=20,valid=points.filter(p=>select(p)!=null),max=Math.max(1,...valid.map(p=>select(p)??0)),span=Math.max(1,to-from)
 const segments:string[]=[];let segment='',previous=0
 for(const p of points){const n=select(p);if(n==null){if(segment)segments.push(segment);segment='';continue};if(previous&&p.time-previous>step*1.5){if(segment)segments.push(segment);segment=''}const x=pad+(p.time-from)/span*(width-pad*2),y=height-pad-(n/max)*(height-pad*2);segment+=`${segment?' L':'M'}${x.toFixed(1)},${y.toFixed(1)}`;previous=p.time}if(segment)segments.push(segment)
 return <section className="card trend-card"><h3>{title}</h3>{valid.length?<><div className="trend-scale"><span>{format(max)}</span><span>{format(0)}</span></div><svg role="img" aria-label={`${title}趋势，缺采区间不连接`} viewBox={`0 0 ${width} ${height}`}><line x1={pad} x2={width-pad} y1={height-pad} y2={height-pad} stroke="currentColor" opacity=".2"/>{segments.map((d,i)=><path key={i} d={d} fill="none" stroke="currentColor" strokeWidth="2"/>)}{valid.length===1&&<circle cx={pad+(valid[0].time-from)/span*(width-pad*2)} cy={height-pad-((select(valid[0])??0)/max)*(height-pad*2)} r="3" fill="currentColor"/>}</svg><div className="trend-times"><small>{date(new Date(from*1000).toISOString())}</small><small>{date(new Date(to*1000).toISOString())}</small></div><details><summary>查看数值</summary><div className="table-wrap trend-values"><table><thead><tr><th>时间</th><th>{title}</th></tr></thead><tbody>{points.map(p=><tr key={p.time}><td>{date(new Date(p.time*1000).toISOString())}</td><td>{select(p)==null?'未知':format(select(p)!)}</td></tr>)}</tbody></table></div></details></>:<Empty title="暂无趋势数据">启用观测并发布后，等待至少两次采集；缺少数据不会补成零。</Empty>}</section>
}
export function AlertList({serviceID}:{serviceID?:string}){
 const qc=useQueryClient(),[history,setHistory]=useState(false)
 const q=useQuery({queryKey:['alerts'],queryFn:()=>api<{items:Alert[]}>('/alerts'),refetchInterval:30000})
 const ack=useMutation({mutationFn:(id:string)=>api(`/alerts/${encodeURIComponent(id)}/acknowledge`,{method:'POST',body:{}}),onSuccess:()=>void qc.invalidateQueries({queryKey:['alerts']})})
 const items=(q.data?.items??[]).filter(a=>(!serviceID||a.service_id===serviceID)&&(history||a.status==='active'||a.status==='unknown')).slice(0,50)
 const labels={active:'告警中',unknown:'状态未知',resolved:'已恢复',disabled:'检查已关闭'}
 return <section className="card observation-alerts" aria-label="站内告警"><div className="section-heading"><h2>站内告警</h2><label className="checkbox"><input type="checkbox" checked={history} onChange={e=>setHistory(e.target.checked)}/>显示恢复与关闭记录</label></div><p className="muted">每分钟核对。指标规则需要完整 5 分钟且至少 20 请求；后台 TCP 来自 Manager。确认告警后仍会继续监测。</p><ErrorBox error={q.error} onRetry={()=>void q.refetch()}/><ErrorBox error={ack.error}/>{q.isPending?<Loading/>:items.length?<ul className="alert-list">{items.map(a=><li key={a.id}><Badge tone={a.status==='active'?'amber':'neutral'}>{labels[a.status]??'状态未知'}</Badge><div><p>{a.message}</p><small>首次 {date(a.first_seen)} · 最近 {date(a.last_seen)}{a.service_id?` · 服务 ID ${a.service_id}`:''}</small></div>{a.acknowledged?<small>已确认</small>:<button className="button button-outline" disabled={ack.isPending} onClick={()=>ack.mutate(a.id)}>确认已知晓</button>}</li>)}</ul>:<Empty title="没有待处理告警">关闭、未知或尚未评估的检查不能证明应用健康；查看观测状态与证书信息。</Empty>}</section>
}
function LogViewer({serviceID,hours}:{serviceID?:string;hours:number}){
 const [method,setMethod]=useState(''),[status,setStatus]=useState(''),[path,setPath]=useState(''),[ip,setIP]=useState(''),[offset,setOffset]=useState(0)
 const filters={method,status,path,ip};const q=useQuery({queryKey:['access-logs',serviceID,method,status,path,ip,offset,hours],queryFn:()=>{const to=Math.floor(Date.now()/1000);const query=new URLSearchParams({from:String(to-Math.min(hours*3600,7*24*3600-60)),to:String(to),limit:'50',offset:String(offset),kind:'access'});if(serviceID)query.set('service_id',serviceID);for(const [k,v]of Object.entries(filters))if(v)query.set(k,v);return api<{items:AccessEvent[]}>('/logs?'+query)},refetchInterval:30000})
 function change(fn:(v:string)=>void,v:string){fn(v);setOffset(0)}
 return <section className="card observation-logs" aria-label="脱敏访问日志"><h2>脱敏访问日志</h2><p className="muted">最近 7 天。路径仅保留安全分类，IP 为 IPv4 /24 或 IPv6 /48 网段；不保存 query、header、Cookie 和请求体。</p><div className="observation-filters"><label>日志方法<select value={method} onChange={e=>change(setMethod,e.target.value)}><option value="">全部方法</option>{['GET','POST','PUT','PATCH','DELETE','HEAD','OPTIONS','CONNECT','TRACE','OTHER'].map(v=><option key={v}>{v}</option>)}</select></label><label>日志状态码<input type="number" min="100" max="599" value={status} placeholder="例如 503" onChange={e=>change(setStatus,e.target.value)}/></label><label>脱敏路径<select value={path} onChange={e=>change(setPath,e.target.value)}><option value="">全部路径分类</option>{['/','/<redacted>','/api/*','/assets/*','/static/*','/health/*','/login/*','/auth/*','/public/*'].map(v=><option key={v}>{v}</option>)}</select></label><label>脱敏 IP 网段<input value={ip} placeholder="例如 192.168.1.0/24" onChange={e=>change(setIP,e.target.value)}/></label></div><ErrorBox error={q.error} onRetry={()=>void q.refetch()}/>{q.isPending?<Loading/>:(q.data?.items??[]).length?<div className="table-wrap"><table><thead><tr><th>时间 / 服务</th><th>请求</th><th>响应</th><th>来源网段</th></tr></thead><tbody>{q.data!.items.map(e=><tr key={`${e.epoch}:${e.sequence}`}><td>{date(e.time)}<small>{e.hostname}</small></td><td>{e.method} <code>{e.path}</code></td><td><Badge tone={(e.status??0)>=500?'amber':'neutral'}>{e.status}</Badge><small>{duration(e.duration_seconds)} · {bytes(e.response_bytes??0)}</small></td><td><code>{e.ip}</code></td></tr>)}</tbody></table></div>:<Empty title="没有匹配的脱敏日志">启用日志并发布后产生请求，或调整筛选条件；采集错误请查看观测状态。</Empty>}<div className="observation-pagination"><button className="button button-outline" disabled={offset===0||q.isFetching} onClick={()=>setOffset(Math.max(0,offset-50))}>上一页</button><span>第 {offset/50+1} 页</span><button className="button button-outline" disabled={(q.data?.items?.length??0)<50||q.isFetching} onClick={()=>setOffset(offset+50)}>下一页</button></div></section>
}
export function DiagnosticPanel({domainID}:{domainID:string}){
 const q=useMutation({mutationFn:()=>api<Diagnostics>('/diagnostics',{method:'POST',body:{domain_id:domainID}})})
 const result=q.data?.domain_id===domainID?q.data:null
 return <section className="card observation-diagnostics" aria-label="域名诊断"><h2>域名诊断</h2><p>点击后从 Manager 查询已生效域名的 DNS / CAA，并通过固定 Caddy 地址检测 TLS。结果与浏览器或外部 Caddy 的网络视角可能不同。</p><button className="button button-outline" disabled={!domainID||q.isPending} onClick={()=>q.mutate()}>{q.isPending?'诊断中…':'检查 DNS / CAA / TLS'}</button><ErrorBox error={q.error} onRetry={()=>q.mutate()}/>{result&&<><small>检查于 {date(result.checked_at)}</small><ul className="diagnostic-list">{result.checks.map((c,i)=><li key={i}><Badge tone={c.status==='pass'?'green':c.status==='fail'?'amber':'neutral'}>{c.status==='pass'?'检查通过':c.status==='fail'?'检测异常':'未知'}</Badge><strong>{c.name}</strong><p>{c.message}</p>{c.values.length>0&&<code>{c.values.join('、')}</code>}</li>)}</ul><h3>最近全实例签发线索</h3>{result.events.length?<ul>{result.events.map(e=><li key={`${e.epoch}:${e.sequence}`}>{diagnosticClass[e.class??'']??'原因未确认'} · {date(e.time)}</li>)}</ul>:<p className="muted">没有近期已索引事件；不表示签发一定成功。</p>}</>}</section>
}
export function TrafficWorkspace({serviceID,domainID,allowServiceFilter=true}:{serviceID?:string;domainID?:string;allowServiceFilter?:boolean}){
 const [hours,setHours]=useState(24),[selected,setSelected]=useState('');const id=serviceID||selected
 const status=useQuery({queryKey:['observability'],queryFn:()=>api<ObservationStatus>('/observability'),refetchInterval:15000})
 const q=useQuery({queryKey:['traffic',id,hours],queryFn:()=>{const to=Math.floor(Date.now()/1000),params=new URLSearchParams({from:String(to-hours*3600),to:String(to)});if(id)params.set('service_id',id);return api<TrafficData>('/traffic?'+params)},refetchInterval:30000})
 const options=useQuery({queryKey:['traffic','',hours],queryFn:()=>{const to=Math.floor(Date.now()/1000);return api<TrafficData>('/traffic?'+new URLSearchParams({from:String(to-hours*3600),to:String(to)}))},enabled:!serviceID&&allowServiceFilter,refetchInterval:30000})
 const current=useQuery({queryKey:['services'],queryFn:()=>api<ServiceList>('/services'),enabled:!serviceID&&allowServiceFilter,refetchInterval:30000})
 const services=[...(options.data?.services??q.data?.services??[]),...(current.data?.published??[])]
 const d=q.data,points=d?.points??[],from=d?.from??Math.floor(Date.now()/1000)-hours*3600,to=d?.to??Math.floor(Date.now()/1000)
 return <div className="traffic-workspace"><div className="notice notice-neutral"><span>{status.error?'无法刷新观测状态；统计仅供历史核对':status.data?.message??'正在读取观测状态…'}</span><small>最近采集 {date(status.data?.last_sample??'')}</small></div><ErrorBox error={status.error} onRetry={()=>void status.refetch()}/>{status.data?.logs_state==='unavailable'&&<p className="notice notice-amber">日志采集不可用，请检查 Caddy 观测模块、日志目录空间与权限。</p>}{status.data?.log_gap&&<p className="notice notice-amber">日志存在缺口；源端报告丢弃 {status.data.dropped_logs??0} 条，已保存的日志仍可查询。</p>}<div className="observation-filters"><label>统计时间<select value={hours} onChange={e=>setHours(Number(e.target.value))}>{[[1,'最近 1 小时'],[24,'最近 24 小时'],[168,'最近 7 天'],[720,'最近 30 天'],[4320,'最近 180 天'],[8759,'最近 365 天']].map(([n,l])=><option key={n} value={n}>{l}</option>)}</select></label>{!serviceID&&allowServiceFilter&&<label>统计服务<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">全部业务服务</option>{selected&&!services.some(s=>s.id===selected)&&<option value={selected}>服务 {selected.slice(0,8)}（当前窗口无记录）</option>}{services.filter((s,i,all)=>all.findIndex(x=>x.id===s.id)===i).map(s=><option key={s.id} value={s.id}>{s.hostname} · {s.id.slice(0,8)}</option>)}</select></label>}<button className="button button-outline" disabled={q.isFetching} onClick={()=>void q.refetch()}>刷新统计</button></div><ErrorBox error={q.error} onRetry={()=>void q.refetch()}/>{q.isPending?<Loading/>:<><TrafficCards stats={d?.summary}/><p className="muted">统计覆盖率 {Math.round((d?.coverage??0)*100)}% · {d?.complete?'当前窗口采集完整':'数据不完整，不能用缺口判断零流量或正常'} · 聚合间隔 {d?.step??'—'} 秒。实际统计区间 {date(new Date(from*1000).toISOString())} 至 {date(new Date(to*1000).toISOString())}（完整聚合桶）。分位数按 bucket 估算；请求流量仅为已读取体字节，响应流量仅为体字节。长连接关闭后统计完整时长。</p><div className="traffic-trends"><Trend title="请求量" points={points} select={p=>p.requests} format={v=>Math.round(v).toLocaleString()} from={from} to={to} step={d?.step??60}/><Trend title="响应体流量" points={points} select={p=>p.response_bytes} format={bytes} from={from} to={to} step={d?.step??60}/><Trend title="5xx 响应" points={points} select={p=>p.five_xx} format={v=>Math.round(v).toLocaleString()} from={from} to={to} step={d?.step??60}/><Trend title="P95 完整响应时长" points={points} select={p=>p.p95} format={duration} from={from} to={to} step={d?.step??60}/></div><details className="card"><summary>延迟与状态分布</summary><p>P50 {duration(d?.summary?.p50)} · P95 {duration(d?.summary?.p95)} · P99 {duration(d?.summary?.p99)} · 首字节 P95 {duration(d?.summary?.first_byte_p95)}</p><p>{Object.entries(d?.summary?.statuses??{}).map(([k,v])=>`${k}：${Math.round(v)}`).join(' · ')||'暂无状态分布'}{d?.summary?.quantile_lower_bound?' · 超出最高有限 bucket 的分位数显示下界':''}</p></details></>}<AlertList serviceID={id}/><LogViewer key={id} serviceID={id} hours={hours}/>{domainID&&<DiagnosticPanel key={domainID} domainID={domainID}/>}</div>
}
